Use proper `self` for Command and related
dropbox/rust-brotli pull request #168
Opened 2024-03-18 19:46 UTC by nyurik

Use `hide whitespace changes` when reviewing

2024-04-06 06:44 UTC, danielrh requested changes
Please resolve TODO's

2024-04-07 07:43 UTC, danielrh commented
pls fix conflicts, thx

2024-04-07 17:41 UTC, nyurik commented
thx, fixed. There is still two functions - `free_cmd` and `free_cmd_inline` - that have not been done yet, but I ran into a minor compilation issue with them - I will fix them in a separate PR

2024-04-18 06:14 UTC, danielrh approved these changes

2024-04-18 06:14 UTC, merged